// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA1jcz9IQ6e_b5rf15UBQCDoCw4sLWIXM',
    appId: '1:567588282549:web:d8da15f46cc8e435041efc',
    messagingSenderId: '567588282549',
    projectId: 'todo-2e28e',
    authDomain: 'todo-2e28e.firebaseapp.com',
    storageBucket: 'todo-2e28e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn_cZpfxBNSwYS5vi_DOJBNH2MCRiRPZs',
    appId: '1:567588282549:android:d29652378d373dd9041efc',
    messagingSenderId: '567588282549',
    projectId: 'todo-2e28e',
    storageBucket: 'todo-2e28e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0R5ENm7iYBK5Dv9-dgiyaMS1-2c51X6E',
    appId: '1:567588282549:ios:9025483d7be4e1dc041efc',
    messagingSenderId: '567588282549',
    projectId: 'todo-2e28e',
    storageBucket: 'todo-2e28e.appspot.com',
    iosBundleId: 'com.todo.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0R5ENm7iYBK5Dv9-dgiyaMS1-2c51X6E',
    appId: '1:567588282549:ios:9025483d7be4e1dc041efc',
    messagingSenderId: '567588282549',
    projectId: 'todo-2e28e',
    storageBucket: 'todo-2e28e.appspot.com',
    iosBundleId: 'com.todo.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA1jcz9IQ6e_b5rf15UBQCDoCw4sLWIXM',
    appId: '1:567588282549:web:a05ffac3d8d92001041efc',
    messagingSenderId: '567588282549',
    projectId: 'todo-2e28e',
    authDomain: 'todo-2e28e.firebaseapp.com',
    storageBucket: 'todo-2e28e.appspot.com',
  );
}
